######################## default configuration ####################
baseURL = "https://ebeno.metraf.me/"
title = "Ebeno"
theme = "godocs-4"
# google analytics
googleAnalytics = "" # example : UA-123-45
# disable language
disableLanguages = [] # disable language from here
defaultContentLanguage = "fr"
# hugo outputs
[outputs]
home = ["HTML", "JSON"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugin
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/search/auto-complete.css"
[[params.plugins.css]]
link = "plugins/featherlight/featherlight.min.css"

# JS Plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/js/all.min.js"
attributes = "crossorigin='anonymous' defer='defer' data-search-pseudo-elements"
[[params.plugins.js]]
link = "plugins/masonry/masonry.min.js"
[[params.plugins.js]]
link = "plugins/featherlight/featherlight.min.js"
[[params.plugins.js]]
link = "plugins/clipboard/clipboard.min.js"
[[params.plugins.js]]
link = "plugins/search/auto-complete.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/search/lunr.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search-page.js"

# site variables
[params.variables]
# Color Variables
primary_color = "#bf9000"
text_color = "#333"
text_color_dark = "#222"
text_color_light = "#999"
body_color = "#fff"
border_color = "#E2E2E2"
black = "#000"
white = "#fff"
light = "#FBFBFB"

# Font Variables
primary_font = "Montserrat:wght@300;400;500;600;700;800"
primary_font_type = "sans-serif"                         # [serif/sans-serif]
secondary_font = ""
secondary_font_type = ""                                 # [serif/sans-serif]
icon_font = "Font Awesome 5 Free"


#################### default parameters ################################
[params]
# meta description
author = "Jean Doukhan"
description = "Site de références pour ébénistes"
# contact form action
contact_form_action = "https://formspree.io/f/xqkjgjyb" # contact form works with https://formspree.io
# feedback form action
feedback_form_action = "https://formspree.io/f/xlevovpl" # contact form works with https://formspree.io

# logo
[params.logo]
main = "logo.png"
favicon = "logo.png"
main_site_link = "https://ebeno.fr"
logo_icon = ""
site_logo = "logo.png"
docs_logo = "nom_seul2.png"

# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.


# Navigation button

[[params.nav_button]]
style = "solid"   # available style: solid, outline
label = "contact"
link = "contact/"


############################# social site ########################
[[params.social]]
title = "Qui suis-je ?"
icon = "fas fa-address-card" # fontawesome icon : https://fontawesome.com/icons
link = "https://jean.doukhan.pro"


[[params.social]]
title = "Mon LinkedIn"
icon = "fab fa-linkedin" # fontawesome icon : https://fontawesome.com/icons
link = "https://www.linkedin.com/in/jean-doukhan/"



[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
weight = 1
# copyright
copyright = "Conçu avec l'aide de [Hugo](https://gohugo.io)"

# banner
[Languages.fr.banner]
title = "Références utiles <br>Des ébénistes"
subtitle = "Le prix  général d'une essence ? Un fournisseur ? Des conseils ? "
image = "park.png"

# feedback
[Languages.fr.feedback]
title = "Avez-vous trouvé ces informations pertinentes ?"
content = "Vos commentaires nous aident à améliorer la plateforme."
positive_placeholder = "Qu'avez-vous aimé sur cette page ?"
negative_placeholder = "Que pouvons-nous améliorer cette page ?"

# call to action
[Languages.fr.call_to_action]
enable = false
title = "Vous avez une question ou une demande ?"
image = "images/cta-illustration.jpg"
content = "N'hésitez pas à faire des retours !"

# call to action button
[Languages.fr.call_to_action.button]
enable = "true"
label = "Ecrire une demande !"
link = "contact/"



[[Languages.fr.menu.footer]]
name = "Ref"
url = "/ref/"
weight = 1

[[Languages.fr.menu.footer]]
name = "Contact"
url = "/contact/"
weight = 2
